name: High vulns Snyk PR scan

on: pull_request

env:
  IMAGE_NAME: dwpdigital/dataworks-kafka-reconciliation

jobs:
  docker-build-and-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requirements
        run: pip install -r ./requirements.txt
      - name: build and test
        run: make tests
      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .
      - name: Run Snyk to check image for high vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE_NAME }}
          args: --file=./Dockerfile --policy-path=./.snyk --severity-threshold=high --exclude-base-image-vulns --org=dwp-dataworks
